name: Specter Composite Action
description: An example for Composite GitHub Action

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  training_center:
    description: The training center
    value: ${{ steps.my-action.outputs.training_center }}

runs:
  using: composite
  steps:
    - run: echo "Hello, ${{ inputs.who-to-greet }}"
      shell: bash

    - run: echo "training_center=Specter" >> $GITHUB_OUTPUT
      id: test-output
      shell: bash

    - run: echo "The training center is ${{ steps.test-output.outputs.training_center }}"
      shell: bash
